# Generated by Django 3.2 on 2022-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.UUIDField(),
        ),
    ]
