# Generated by Django 3.2 on 2022-06-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='post_id',
        ),
        migrations.AddField(
            model_name='likepost',
            name='post',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='core.post'),
            preserve_default=False,
        ),
    ]
