# Generated by Django 3.2 on 2022-06-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220603_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_img',
            field=models.ImageField(default='default_cover_img.jpg', upload_to='profile_images'),
        ),
    ]
