# Generated by Django 3.2 on 2022-06-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customname'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetPasswordLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
